### ISSUE TITLE
use uploads.scratch

### ISSUE THREAD

**Issue by gosoccerboy5** [rirurin/postpercent#2]
you are currently using [cdn2.scratch](//cdn2.scratch) but i like [uploads.scratch](//uploads.scratch)

**Comment by rirurin** [comment]
same
i'll add that for the user page only - I imagine there's a speed disadvantage when trying to load 100 full sized images like on the leaderboards, but 1 on the user screen should be fine

**Comment by rirurin** [comment]
added
