### ISSUE TITLE
Forum statistics are unreadable in light mode

### ISSUE THREAD

**Issue by Looky1173** [rirurin/postpercent#6]
![image](https://user-images.githubusercontent.com/60521810/123382581-64527880-d592-11eb-803c-2822809677a8.png)
**Issue:** Forum statistics are unreadable or very difficult to decipher in light mode.

**Comment by rirurin** [comment]
Is your device's system theme set to light mode, because I know I didn't really consider people who had light mode as their system theme when I wrote the script to determine the colors of those category boxes

**Comment by Looky1173** [comment]
I used Task Scheduler in Windows to automatically switch my theme based on what time it is.

**Comment by rirurin** [comment]
> I use Task Scheduler in Windows to automatically switch my theme based on what time it is.

That's pretty cool
I recently pushed an update that did some work with the theming system, so are you still experiencing these issues now?

**Comment by Looky1173** [comment]
![image](https://user-images.githubusercontent.com/60521810/123608401-037ba800-d7ff-11eb-9f41-2e479061ec31.png)
> I recently pushed an update that did some work with the theming system, so are you still experiencing these issues now?
As you can see, not anymore! Thank you for fixing this!
