### ISSUE TITLE
If a user returns a 404 page on Scratch, put that the user got 'yeeted out of existence' or something similar

### ISSUE THREAD

**Issue by SausageMcSauce** [rirurin/postpercent#7]
In title.

Another way of detected users who were deleted on Scratch are users whose icons on their PostPercent user page [(such as this one)](https://postpercent.rirurin.com/users/asivi) go to https://uploads.scratch.mit.edu/users/avatars/null.png .

I think a notice saying a user had been 'yeeted out of existence' could go in the box where the Ocular status would, as many users who are deleted in the first page of the list of Scratchers with the most posts do not (and will never) have an Ocular status.

**Comment by rirurin** [comment]
Not sure if i'll specifically use the text "yeeted out of existence", but I may add a message to indicate if a user has been deleted from the site

**Comment by SausageMcSauce** [comment]
Another idea for Scratch-deleted users: If possible, make where their ocular colo(u)r would be on this thing's stat pages a magenta and black checkerboard (like missing textures in several things)
